embed_assets: on

javascripts:
  base: 
    - public/javascripts/jquery-1.5.2.min.js
    - public/javascripts/jquery.treeview.js
    - public/javascripts/jquery-ui-1.8.12.custom.min.js
    - public/javascripts/ie.js
    - public/javascripts/slide.js
  # - DD_belatedPNG
stylesheets:
  base: 
    - public/stylesheets/jquery.treeview.css
    - public/stylesheets/jquery-ui-1.8.12.custom.css
    - public/stylesheets/idea.css

